---
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
  - \usepackage{placeins}
  
output:
  pdf_document: 
        fig_caption: yes
        number_sections: yes
  word_document: default
  html_document: 
        toc: true
        
bibliography: bibliography.bib
---

```{r setup, set-options, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,
               cache=TRUE, autodep=TRUE, cache.comments=FALSE,
               message=FALSE, warning=FALSE, tidy = FALSE)
options(width = 400, kableExtra.latex.load_packages = FALSE, knitr.table.format = "latex")

```

```{r child = 'Chapters/titlepage.Rmd'}
```

\newpage

\tableofcontents

\newpage


```{r child = 'Chapters/introduction.Rmd'}
```

\FloatBarrier

```{r child = 'Chapters/data.Rmd'}
```

\FloatBarrier

```{r child = 'Chapters/eda.Rmd'}
```


\FloatBarrier

```{r child = 'Chapters/naivemodel.Rmd'}
```

\FloatBarrier

# Models

Not sure why there is nothing here.  

\FloatBarrier

# Conclusion  

Not sure why there is nothing here.  

\FloatBarrier


\newpage

\appendix \section{Appendices}

\subsection{Summary Statistics for Predictors} 

```{r summaries, echo = FALSE, comment = NA}

stats <- basicStats(use_data[-c(40,41)])[c('Mean', 'Median', 'Stdev', 'Minimum', 'Maximum', 'NAs'),]

kable(round(t(stats), 2), booktabs = TRUE) %>% 
        kable_styling(font_size = 8, latex_options = c('striped', 'scale_down', 'hold_position'))

```

\newpage

# References