\subsection{k-Nearest Neighbor} 

```{r knn_results, echo = FALSE}

# Create a data frame to hold the results
knn_results <- data.frame(Model = character()
                             ,Data = character()
                             ,Accuracy = numeric()
                             ,Kappa = numeric()
                             ,F1 = numeric()
                             ,ROC = numeric()
                             ,Sensitivity = numeric()
                             ,Specificity = numeric())
```

```{r knn_models, echo = FALSE}

# Enable parallel processing and reserve resources
#cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
#registerDoParallel(cluster)

# Set up training conditions - must use LOOCV
fitControl <- trainControl(method = "LOOCV"
                           ,classProbs = TRUE 
                           ,summaryFunction = twoClassSummary
                           ,savePredictions = 'final')

# Full data set
#set.seed(1234)
#knn.model.ud <- caret::train(Label ~ .
#                          ,data = use_data
#                          ,method = "knn"
#                          ,trControl = fitControl
#                          ,metric = "ROC" 
#                          ,preProc = c("center", "scale")
#                          ,tuneLength = 20)

knn.model.ud <- readRDS('../../Models/knn_use_data.rds')

# Get the confusion matrix
knn.cm.ud <- caret::confusionMatrix(knn.model.ud$pred$pred, knn.model.ud$pred$obs, mode = "everything")

# Get the performance metrics from the model and save for comparison
performance <- getTrainPerf(knn.model.ud)
knn_results <- rbind(knn_results
                        ,data.frame(Model = 'kNN'
                        ,Data = 'Full'
                        ,Accuracy = knn.cm.ud$overall[1]
                        ,Kappa = knn.cm.ud$overall[2]
                        ,F1 = knn.cm.ud$byClass[7]
                        ,ROC = performance[,1]
                        ,Sensitivity = performance[,2]
                        ,Specificity = performance[,3]))

# RFE selection data set
#set.seed(1234)
#knn.model.md <- caret::train(Label ~ .
#                             ,data = model_data
#                             ,method = "knn"
#                             ,trControl = fitControl
#                             ,metric = "ROC" 
#                             ,preProc = c("center", "scale")
#                             ,tuneLength = 20)

knn.model.md <- readRDS('../../Models/knn_model_data.rds')

# Get the confusion matrix
knn.cm.md <- caret::confusionMatrix(knn.model.md$pred$pred, knn.model.md$pred$obs, mode = "everything")

# Get the performance metrics from the model and save for comparison
performance <- getTrainPerf(knn.model.md)
knn_results <- rbind(knn_results
                        ,data.frame(Model = 'kNN'
                        ,Data = 'RFE Selection'
                        ,Accuracy = knn.cm.md$overall[1]
                        ,Kappa = knn.cm.md$overall[2]
                        ,F1 = knn.cm.md$byClass[7]
                        ,ROC = performance[,1]
                        ,Sensitivity = performance[,2]
                        ,Specificity = performance[,3]))

# Low correlation data set
#set.seed(1234)
#knn.model.lc <- caret::train(Label ~ .
#                             ,data = use_data_lc
#                             ,method = "knn"
#                             ,trControl = fitControl
#                             ,metric = "ROC" 
#                             ,preProc = c("center", "scale")
#                             ,tuneLength = 20)

knn.model.lc <- readRDS('../../Models/knn_use_data_lc.rds')

# Get the confusion matrix
knn.cm.lc <- caret::confusionMatrix(knn.model.lc$pred$pred, knn.model.lc$pred$obs, mode = "everything")

# Get the performance metrics from the model and save for comparison
performance <- getTrainPerf(knn.model.lc)
knn_results <- rbind(knn_results
                        ,data.frame(Model = 'kNN'
                        ,Data = 'Low Correlation'
                        ,Accuracy = knn.cm.lc$overall[1]
                        ,Kappa = knn.cm.lc$overall[2]
                        ,F1 = knn.cm.lc$byClass[7]
                        ,ROC = performance[,1]
                        ,Sensitivity = performance[,2]
                        ,Specificity = performance[,3]))

rownames(knn_results) <- NULL

# Disable parallel processing and release resources
#stopCluster(cluster)
#registerDoSEQ()

```

```{r knn_roc, echo = FALSE}

kable(knn_results, caption = "kNN Model Results", booktabs = TRUE) %>% 
        kable_styling(font_size = 8, latex_options = c("striped", "hold_position"))

knn.ROC <- roc(knn.model.md$pred$obs, knn.model.md$pred$Normal)
plot(knn.ROC, col = 'blue', main = paste('kNN - Area under the curve (AUC):', round(auc(knn.ROC),2)))

```

```{r knn_plot, echo = FALSE}

plot(knn.model.md)

```