# Data

The data consists of 2,606 observations from `r length(unique(full$PatientNumMasked))` patients and is split between six lung segments. The six segments represent the right upper, right middle, right lower, left upper, left middle, and left lower regions of the lung images. The data is provided in an MS Excel spreadsheet, with a separate tab for each segment.

Each segment contains 39 continuous variables and a categorical response variable labeled as '0' for 'Normal', those without the disease, and '1' for 'Abnormal' when Pneumoconiosis is present. The 39 continuous features fall into two categories, intensity based and co-occurrence matrix based. To obtain the intensity based features, a set of six features computed from the histogram of intensity values – mean, standard deviation, skewness, kurtosis, energy and entropy were extracted. Filters were then applied to the images. Of the 222 features that this method generated, only 34 were supplied for the case study.

Five additional features were extracted for the co-occurence matrix based variables. These features include energy, entropy, local homogeneity, correlation and inertia and are determined by the gray level co-occurrence matrix that was computed for the ROI. 

